apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnettektongithub221024
  janus-idp.io/tekton: dotnettektongithub221024
  backstage.io/kubernetes-id: dotnettektongithub221024
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnettektongithub221024
resources:
- deployment.yaml
- route.yaml
- service.yaml
