apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnettektongithub221024
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnettektongithub221024 
  name: dotnettektongithub221024
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnettektongithub221024 
